In [2]:
import numpy as np
from scipy.spatial.distance import pdist, squareform
import time
import sys

# Function to calculate time and space complexity
def calculate_complexities(m, n):
    # Time complexity (Offline)
    time_complexity_user_based = m * (n**2)  # O(m * n^2)
    time_complexity_item_based = (n**2) * m  # O(n^2 * m)

    # Space complexity (Offline)
    space_complexity_user_based = m**2  # O(m^2)
    space_complexity_item_based = n**2  # O(n^2)

    return time_complexity_user_based, time_complexity_item_based, space_complexity_user_based, space_complexity_item_based

In [3]:

# Generate a 5x5 random user-item rating matrix
np.random.seed(42)  # For reproducibility
user_item_matrix = np.random.randint(1, 6, (5, 5))

# Print the user-item matrix
print("User-Item Matrix:")
print(user_item_matrix)

User-Item Matrix:
[[4 5 3 5 5]
 [2 3 3 3 5]
 [4 3 5 2 4]
 [2 4 5 1 4]
 [2 5 4 1 1]]


In [4]:
# Calculate cosine similarity
start_time = time.time()
cosine_similarities = 1 - squareform(pdist(user_item_matrix, metric='cosine'))
time_taken = time.time() - start_time

# Print the cosine similarity matrix
print("\nCosine Similarity Matrix:")
print(cosine_similarities)


Cosine Similarity Matrix:
[[1.         0.96214047 0.90837374 0.86360086 0.80225745]
 [0.96214047 1.         0.92637102 0.91643971 0.76018915]
 [0.90837374 0.92637102 1.         0.95630337 0.85427585]
 [0.86360086 0.91643971 0.95630337 1.         0.90771875]
 [0.80225745 0.76018915 0.85427585 0.90771875 1.        ]]


In [5]:
# Space used in memory for cosine similarity
space_used = sys.getsizeof(cosine_similarities)

# Calculate complexities
time_user, time_item, space_user, space_item = calculate_complexities(m=5, n=5)

# Print time and space complexity results
print("\nTime and Space Complexity Results:")
print(f"Time Taken for Cosine Similarity (seconds): {time_taken}")
print(f"Space Used for Cosine Similarity (bytes): {space_used}")
print(f"Time Complexity (User-Based): {time_user}")
print(f"Time Complexity (Item-Based): {time_item}")
print(f"Space Complexity (User-Based): {space_user}")
print(f"Space Complexity (Item-Based): {space_item}")


Time and Space Complexity Results:
Time Taken for Cosine Similarity (seconds): 0.0014216899871826172
Space Used for Cosine Similarity (bytes): 328
Time Complexity (User-Based): 125
Time Complexity (Item-Based): 125
Space Complexity (User-Based): 25
Space Complexity (Item-Based): 25


# **Another Code:**

In [6]:
import numpy as np

# Generate a 5x5 random user-item rating matrix
np.random.seed(42)  # For reproducibility
user_item_matrix = np.random.randint(1, 6, (5, 5))

# Print the user-item matrix
print("User-Item Matrix:")
print(user_item_matrix)

User-Item Matrix:
[[4 5 3 5 5]
 [2 3 3 3 5]
 [4 3 5 2 4]
 [2 4 5 1 4]
 [2 5 4 1 1]]


In [7]:
from scipy.spatial.distance import pdist, squareform
import time

# Function to calculate time complexity
def calculate_time_complexity(m, n):
    time_complexity_user_based = m * (n**2)  # O(m * n^2)
    time_complexity_item_based = (n**2) * m  # O(n^2 * m)
    return time_complexity_user_based, time_complexity_item_based

# Print the time complexity equations for user-based and item-based methods
m, n = user_item_matrix.shape
time_user, time_item = calculate_time_complexity(m, n)

print("\nTime Complexity Results:")
print(f"Time Complexity (User-Based): O({m} * {n}^2) = {time_user}")
print(f"Time Complexity (Item-Based): O({n}^2 * {m}) = {time_item}")

# Calculate and measure execution time for cosine similarity (user-based)
start_time_user = time.time()
cosine_similarities_user = 1 - squareform(pdist(user_item_matrix, metric='cosine'))
time_taken_user = time.time() - start_time_user

print("\nExecution Time for Cosine Similarity (User-Based):")
print(f"{time_taken_user} seconds")


Time Complexity Results:
Time Complexity (User-Based): O(5 * 5^2) = 125
Time Complexity (Item-Based): O(5^2 * 5) = 125

Execution Time for Cosine Similarity (User-Based):
0.0018377304077148438 seconds


In [10]:
import sys

# Function to calculate space complexity
def calculate_space_complexity(m, n):
    space_complexity_user_based = m**2  # O(m^2)
    space_complexity_item_based = n**2  # O(n^2)
    return space_complexity_user_based, space_complexity_item_based

# Print the space complexity equations for user-based and item-based methods
space_user, space_item = calculate_space_complexity(m, n)

print("\nSpace Complexity Results:")
print(f"Space Complexity (User-Based): O({m}^2) = {space_user}")
print(f"Space Complexity (Item-Based): O({n}^2) = {space_item}")

# Measure space used for the cosine similarity matrix (user-based)
space_used_user = sys.getsizeof(cosine_similarities_user)

print("\nSpace Used for Cosine Similarity (User-Based):")
print(f"{space_used_user} bytes")


Space Complexity Results:
Space Complexity (User-Based): O(5^2) = 25
Space Complexity (Item-Based): O(5^2) = 25

Space Used for Cosine Similarity (User-Based):
328 bytes


In [11]:
# Transpose the user-item matrix for item-based method
item_item_matrix = user_item_matrix.T

# Calculate and measure execution time for cosine similarity (item-based)
start_time_item = time.time()
cosine_similarities_item = 1 - squareform(pdist(item_item_matrix, metric='cosine'))
time_taken_item = time.time() - start_time_item

print("\nExecution Time for Cosine Similarity (Item-Based):")
print(f"{time_taken_item} seconds")

# Measure space used for the cosine similarity matrix (item-based)
space_used_item = sys.getsizeof(cosine_similarities_item)

print("\nSpace Used for Cosine Similarity (Item-Based):")
print(f"{space_used_item} bytes")


Execution Time for Cosine Similarity (Item-Based):
0.0077893733978271484 seconds

Space Used for Cosine Similarity (Item-Based):
328 bytes
