In [2]:
import numpy as np

# Function to generate a random user-item matrix with some missing values (NaNs)
def generate_random_matrix(n_users, n_items, sparsity=0.2):
    matrix = np.random.rand(n_users, n_items)
    mask = np.random.rand(n_users, n_items) > sparsity  # Create a sparsity mask
    matrix[mask] = np.nan  # Set random entries to NaN (missing values)
    return matrix

# Matrix Factorization using Stochastic Gradient Descent (SGD)
def matrix_factorization_sgd(R, num_features, learning_rate=0.01, reg_param=0.02, num_iterations=1000):
    """
    Perform matrix factorization using Stochastic Gradient Descent (SGD).
    :param R: User-item matrix with missing values (NaNs)
    :param num_features: Number of latent features for matrix factorization
    :param learning_rate: Learning rate for SGD
    :param reg_param: Regularization parameter to avoid overfitting
    :param num_iterations: Number of SGD iterations
    :return: P (user feature matrix), Q (item feature matrix)
    """
    # Initialize user and item matrices with random values
    num_users, num_items = R.shape
    P = np.random.rand(num_users, num_features)  # User latent feature matrix
    Q = np.random.rand(num_items, num_features)  # Item latent feature matrix

    # Iterate through the training process
    for iteration in range(num_iterations):
        for i in range(num_users):
            for j in range(num_items):
                if not np.isnan(R[i, j]):  # Only update for known ratings
                    error_ij = R[i, j] - np.dot(P[i, :], Q[j, :].T)  # Calculate error
                    # Update the latent factors using SGD with regularization
                    P[i, :] += learning_rate * (2 * error_ij * Q[j, :] - reg_param * P[i, :])
                    Q[j, :] += learning_rate * (2 * error_ij * P[i, :] - reg_param * Q[j, :])

        # Optionally, print the error every few iterations
        if iteration % 100 == 0:
            error = 0
            for i in range(num_users):
                for j in range(num_items):
                    if not np.isnan(R[i, j]):
                        error += (R[i, j] - np.dot(P[i, :], Q[j, :].T)) ** 2
            print(f"Iteration {iteration} - error: {error}")

    return P, Q

# Reconstruct the matrix by multiplying the user and item matrices
def reconstruct_matrix(P, Q):
    return np.dot(P, Q.T)

# Predict missing values in the user-item matrix
def predict_missing_values(R, P, Q):
    predicted_matrix = reconstruct_matrix(P, Q)
    return predicted_matrix

# Main execution
if __name__ == "__main__":
    n_users = 5  # Number of users
    n_items = 6  # Number of items
    num_features = 3  # Number of latent features for matrix factorization

    # Step 1: Generate a random matrix (user-item interaction matrix)
    R = generate_random_matrix(n_users, n_items)
    print("Original User-Item Matrix (with missing values):")
    print(np.round(R, 2))

    # Step 2: Perform matrix factorization using SGD
    P, Q = matrix_factorization_sgd(R, num_features, num_iterations=1000, learning_rate=0.01, reg_param=0.02)

    # Step 3: Predict the missing values
    predicted_matrix = predict_missing_values(R, P, Q)
    print("\nPredicted User-Item Matrix:")
    print(np.round(predicted_matrix, 2))

    # Step 4: Reconstruct the original matrix (for comparison)
    reconstructed_matrix = reconstruct_matrix(P, Q)
    print("\nReconstructed User-Item Matrix (after factorization):")
    print(np.round(reconstructed_matrix, 2))


Original User-Item Matrix (with missing values):
[[ nan  nan  nan  nan  nan  nan]
 [ nan 0.67 0.82  nan  nan  nan]
 [ nan 0.91  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan 0.09]]
Iteration 0 - error: 0.5429643290919917
Iteration 100 - error: 0.006611896753902188
Iteration 200 - error: 0.0004975809315759102
Iteration 300 - error: 0.00027407089661859736
Iteration 400 - error: 0.0002609918735961719
Iteration 500 - error: 0.0002660502605675207
Iteration 600 - error: 0.0002731907055966697
Iteration 700 - error: 0.0002801888739114739
Iteration 800 - error: 0.00028668454816026853
Iteration 900 - error: 0.0002926243440567916

Predicted User-Item Matrix:
[[0.71 0.86 0.93 0.4  1.03 0.5 ]
 [0.61 0.66 0.81 0.21 0.93 0.37]
 [0.79 0.9  0.9  0.45 1.03 0.45]
 [1.01 0.98 0.56 0.71 0.82 0.17]
 [1.07 0.98 0.51 0.71 0.82 0.09]]

Reconstructed User-Item Matrix (after factorization):
[[0.71 0.86 0.93 0.4  1.03 0.5 ]
 [0.61 0.66 0.81 0.21 0.93 0.37]
 [0.79 0.9  0.9  0.45 1

In [3]:
import numpy as np
import time

# Function to generate a random user-item matrix with some missing values (NaNs)
def generate_random_matrix(n_users, n_items, sparsity=0.2):
    matrix = np.random.rand(n_users, n_items)
    mask = np.random.rand(n_users, n_items) > sparsity  # Create a sparsity mask
    matrix[mask] = np.nan  # Set random entries to NaN (missing values)
    return matrix

# Matrix Factorization using Stochastic Gradient Descent (SGD)
def matrix_factorization_sgd(R, num_features, learning_rate=0.01, reg_param=0.02, num_iterations=1000):
    """
    Perform matrix factorization using Stochastic Gradient Descent (SGD).
    :param R: User-item matrix with missing values (NaNs)
    :param num_features: Number of latent features for matrix factorization
    :param learning_rate: Learning rate for SGD
    :param reg_param: Regularization parameter to avoid overfitting
    :param num_iterations: Number of SGD iterations
    :return: P (user feature matrix), Q (item feature matrix)
    """
    # Initialize user and item matrices with random values
    num_users, num_items = R.shape
    P = np.random.rand(num_users, num_features)  # User latent feature matrix
    Q = np.random.rand(num_items, num_features)  # Item latent feature matrix

    # Measure the start time of the matrix factorization process
    start_time = time.time()

    # Iterate through the training process
    for iteration in range(num_iterations):
        for i in range(num_users):
            for j in range(num_items):
                if not np.isnan(R[i, j]):  # Only update for known ratings
                    error_ij = R[i, j] - np.dot(P[i, :], Q[j, :].T)  # Calculate error
                    # Update the latent factors using SGD with regularization
                    P[i, :] += learning_rate * (2 * error_ij * Q[j, :] - reg_param * P[i, :])
                    Q[j, :] += learning_rate * (2 * error_ij * P[i, :] - reg_param * Q[j, :])

        # Optionally, print the error every few iterations
        if iteration % 100 == 0:
            error = 0
            for i in range(num_users):
                for j in range(num_items):
                    if not np.isnan(R[i, j]):
                        error += (R[i, j] - np.dot(P[i, :], Q[j, :].T)) ** 2
            print(f"Iteration {iteration} - error: {error}")

    # Measure the end time of the matrix factorization process
    end_time = time.time()
    elapsed_time = end_time - start_time  # Time taken for matrix factorization

    print(f"\nMatrix factorization took {elapsed_time:.4f} seconds for {num_iterations} iterations.")

    return P, Q, elapsed_time

# Reconstruct the matrix by multiplying the user and item matrices
def reconstruct_matrix(P, Q):
    return np.dot(P, Q.T)

# Predict missing values in the user-item matrix
def predict_missing_values(R, P, Q):
    predicted_matrix = reconstruct_matrix(P, Q)
    return predicted_matrix

# Main execution
if __name__ == "__main__":
    n_users = 5  # Number of users
    n_items = 6  # Number of items
    num_features = 3  # Number of latent features for matrix factorization
    num_iterations = 1000  # Number of iterations for SGD

    # Step 1: Generate a random matrix (user-item interaction matrix)
    R = generate_random_matrix(n_users, n_items)
    print("Original User-Item Matrix (with missing values):")
    print(np.round(R, 2))

    # Step 2: Perform matrix factorization using SGD
    P, Q, elapsed_time = matrix_factorization_sgd(R, num_features, num_iterations=num_iterations, learning_rate=0.01, reg_param=0.02)

    # Step 3: Predict the missing values
    predicted_matrix = predict_missing_values(R, P, Q)
    print("\nPredicted User-Item Matrix:")
    print(np.round(predicted_matrix, 2))

    # Step 4: Reconstruct the original matrix (for comparison)
    reconstructed_matrix = reconstruct_matrix(P, Q)
    print("\nReconstructed User-Item Matrix (after factorization):")
    print(np.round(reconstructed_matrix, 2))

    # Time Complexity of the Matrix Factorization Process (Empirical)
    total_operations = n_users * n_items * num_iterations
    print(f"\nEmpirical Time Complexity: ~O({total_operations})")


Original User-Item Matrix (with missing values):
[[ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan 0.39  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan 0.75]
 [ nan  nan  nan  nan  nan  nan]]
Iteration 0 - error: 0.015019233857983698
Iteration 100 - error: 0.00015572740580339505
Iteration 200 - error: 0.00013769339709648412
Iteration 300 - error: 0.00013580028172268077
Iteration 400 - error: 0.00013828986607573548
Iteration 500 - error: 0.0001414203820425016
Iteration 600 - error: 0.00014455953039796703
Iteration 700 - error: 0.00014761065448610965
Iteration 800 - error: 0.00015055666709735906
Iteration 900 - error: 0.0001533927918162002

Matrix factorization took 0.1174 seconds for 1000 iterations.

Predicted User-Item Matrix:
[[1.11 0.8  0.73 0.39 1.27 1.17]
 [0.36 0.47 0.54 0.38 0.39 0.36]
 [0.65 0.54 0.53 0.34 0.73 0.67]
 [0.68 0.72 0.77 0.4  0.79 0.74]
 [0.86 1.07 1.2  0.69 0.99 0.93]]

Reconstructed User-Item Matrix (after factorization):
[[1.11 0.8  0.73 0